version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: yourusername/yourlaravelapp
        container_name: yourlaravelapp
        restart: unless-stopped
        ports:
            - "8000:80"
        environment:
            - APACHE_RUN_USER=#1000
        depends_on:
            - db
        networks:
            - app-network

    db:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: yourdbname
            MYSQL_USER: yourdbuser
            MYSQL_PASSWORD: yourdbpassword
            MYSQL_ROOT_PASSWORD: yourrootdbpassword
        ports:
            - "3306:3306"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
