version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel/ci-cd
        container_name: laravel-ci-cd
        restart: unless-stopped
        ports:
            - "80:80"
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=your_database_name
            - DB_USERNAME=your_database_username
            - DB_PASSWORD=your_database_password
#        depends_on:
#            - db
        networks:
            - databse-network
        entrypoint: /usr/local/bin/entrypoint.sh
        volumes:
            - laravel_storage:/var/www/html/storage

networks:
    databse-network:
        external: true

volumes:
    laravel_storage:
