version: '3'

services:
    # Laravel app service
    app:
        image: php:8.2-alpine
        container_name: laravel-app
        working_dir: /var/www/html
        volumes:
            - ./laravel-app:/var/www/html
        command: php -S 0.0.0.0:80 -t public
        ports:
            - "8080:80"
        depends_on:
            - mysql
        networks:
            - laravel-net

    # MySQL service
    mysql:
        image: mysql:latest
        container_name: mysql-container
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password
            MYSQL_ROOT_PASSWORD: root_password
        volumes:
            - ./mysql-data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel-net

networks:
    laravel-net:
        driver: bridge
