version: '3'

services:
  # PHP-Alpine service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-container
    ports:
      - "8080:80"
    networks:
      - app-net

  # MySQL service
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
