version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: yourusername/yourlaravelapp
        container_name: yourlaravelapp
        restart: unless-stopped
        ports:
            - "8001:80"
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=your_database_name
            - DB_USERNAME=your_database_username
            - DB_PASSWORD=your_database_password
        depends_on:
            - db
        networks:
            - app-network

    db:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: your_database_name
            MYSQL_USER: your_database_username
            MYSQL_PASSWORD: your_database_password
            MYSQL_ROOT_PASSWORD: your_root_database_password
        ports:
            - "3306:3306"
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: your_root_database_password
        ports:
            - "8080:80"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
