name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: laravel-ci-cd
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: Clone and Pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            test -d $PROJECT_NAME || git clone https://github.com/${{github.repository}}.git
            cd $PROJECT_NAME
            git pull


      - name: Docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ${{github.repository_name}}
            docker compose build
            docker compose up -d
